language: ruby
sudo: false

cache:
  bundler: true

before_install:
  - gem update --system
rvm:
  - 2.3.3
  - 2.4.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.0.1"
